### ISSUE TITLE
Potential dependency conflicts between panw-utils and cryptography

### ISSUE THREAD

**Issue by NeolithEra** [Dapacruz/panw-utils#2]
Hi, as shown in the following full dependency graph of **_panw-utils_**, **_panw-utils_** requires **_cryptography ==2.7_**, **_ netmiko_** requires **_paramiko >=2.4.3_** (**_paramiko 2.7.1_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_paramiko 2.7.1_** transitively introduces **_cryptography >=2.5_**.

Obviously, there are multiple version constraints set for **_cryptography_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_cryptography 1.2.1_** (i.e., the newest version satisfying constraint **_==2.7_**) is the actually installed version.

Although the first found package version **_cryptography 1.2.1_** just satisfies the later dependency constraint （**_cryptography ==2.7_**), such installed version is very close to the upper bound of the version constraint of cryptography specified by **_paramiko 2.7.1_**. 

Once **_paramiko_** upgrades，its newest version will be installed, as **_panw-utils_** does not specify the upper bound of version constraint for **_paramiko_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_paramiko_** version introduces a higher version of **_cryptography_**, violating its another version constraint **_==2.7_**.

According to the release history of paramiko, it habitually upgrates Cryptography in its recent releases. For instance, paramiko 2.3.0 upgrated Cryptography’s constraint from **_>=1.1 to >=1.5_**,and paramiko 2.5.0 upgrated Cryptography’s constraint from **_>=1.5 to >=2.5_**. 

As such, it is a warm warning of a potential dependency conflict issue for panw-utils.

### Dependency tree
```
panw-utils - 0.5.9
| +- cryptography(install version:2.7 version range:==2.7)
| +- netmiko(install version:2.4.2 version range:==2.4.2)
| | +- enum34(install version:1.1.10 version range:*)
| | +- ipaddress(install version:1.0.23 version range:*)
| | +- paramiko(install version:2.7.1 version range:>=2.4.3)
| | | +- bcrypt(install version:3.1.7 version range:>=3.1.3)
| | | +- cryptography(install version:2.7 version range:>=2.5)
| | | +- pynacl(install version:1.3.0 version range:>=1.0.1)
| | | | +- six(install version:1.14.0 version range:*)
| | +- pyserial(install version:3.4 version range:*)
| | +- scp(install version:0.13.2 version range:>=0.13.2)
| | | +- paramiko(install version:2.7.1 version range:*)
| | | | +- bcrypt(install version:3.1.7 version range:>=3.1.3)
| | | | +- cryptography(install version:2.7 version range:>=2.5)
| | | | +- pynacl(install version:1.3.0 version range:>=1.0.1)
| | +- setuptools(install version:46.1.3 version range:>=38.4.0)
| | +- textfsm(install version:1.1.0 version range:*)
| | | +- future(install version:0.18.2 version range:*)
| | | +- six(install version:1.14.0 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_cryptography_** to be **_>=2.7_**.
2.	Remove your direct dependency **_cryptography_**, and use the **_cryptography_** transitively introduced by **_paramiko_**.
.
@Dapacruz  Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by NeolithEra** [comment]
@Dapacruz，Could you help me review this issue? Thx :p

**Comment by dapacruz** [comment]
I updated the requirements versions and added paramiko to mitigate dependency issues. @NeolithEra thank you for reporting this.
